import type { Workspace, Booking, Event, Plan, Review, BlogPost, Invoice, User, Notification, AnalyticsData } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Alex Rivera",
    email: "alex@example.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    role: "freelancer",
    plan: "professional",
    joinedAt: "2024-01-15",
    phone: "+1 555 0101",
    company: "Freelance Designer",
    bio: "UI/UX designer with 8+ years of experience building digital products.",
    location: "San Francisco, CA",
    verified: true,
  },
  {
    id: "u2",
    name: "Sarah Chen",
    email: "sarah@techstartup.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    role: "startup",
    plan: "enterprise",
    joinedAt: "2024-02-20",
    phone: "+1 555 0102",
    company: "TechFlow Inc.",
    bio: "Co-founder at TechFlow building the future of team collaboration.",
    location: "New York, NY",
    verified: true,
  },
  {
    id: "u3",
    name: "Marcus Johnson",
    email: "marcus@spaces.com",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    role: "owner",
    plan: "professional",
    joinedAt: "2023-11-05",
    phone: "+1 555 0103",
    company: "Urban Spaces LLC",
    bio: "Workspace entrepreneur with 3 locations across downtown.",
    location: "Chicago, IL",
    verified: true,
  },
  {
    id: "u4",
    name: "Emma Wilson",
    email: "emma@community.co",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    role: "community",
    plan: "professional",
    joinedAt: "2024-03-10",
    company: "Spacebility Community",
    bio: "Building vibrant communities of innovators and creators.",
    location: "Austin, TX",
    verified: true,
  },
  {
    id: "u5",
    name: "James Park",
    email: "james@spacebility.com",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    role: "admin",
    plan: "enterprise",
    joinedAt: "2023-09-01",
    company: "Spacebility HQ",
    bio: "Platform administrator overseeing all operations.",
    location: "Seattle, WA",
    verified: true,
  },
];

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "ws1",
    name: "The Innovation Hub",
    type: "hot-desk",
    location: "Downtown SF",
    address: "100 Market St, San Francisco, CA 94105",
    city: "San Francisco",
    country: "USA",
    pricePerHour: 25,
    pricePerDay: 75,
    pricePerMonth: 850,
    rating: 4.9,
    reviewCount: 142,
    capacity: 80,
    available: true,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=500&fit=crop",
    ],
    amenities: ["Wi-Fi", "Coffee", "Printing", "Phone Booths", "24/7 Access", "Parking"],
    description: "San Francisco's premier innovation hub at the heart of the tech district. Features state-of-the-art facilities, fast fiber internet, and a vibrant community of innovators.",
    ownerId: "u3",
    ownerName: "Marcus Johnson",
    tags: ["Tech", "Startup", "Community"],
    featured: true,
    occupancy: 85,
  },
  {
    id: "ws2",
    name: "SkyView Executive Suites",
    type: "private-office",
    location: "Midtown Manhattan",
    address: "350 5th Ave, New York, NY 10118",
    city: "New York",
    country: "USA",
    pricePerHour: 80,
    pricePerDay: 350,
    pricePerMonth: 3500,
    rating: 4.8,
    reviewCount: 89,
    capacity: 20,
    available: true,
    images: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1564069114553-7215e1ff1890?w=800&h=500&fit=crop",
    ],
    amenities: ["Wi-Fi", "Receptionist", "Mail Handling", "Conference Rooms", "Catering", "City Views"],
    description: "Premium executive suites with panoramic Manhattan views. Perfect for established businesses requiring a prestigious address and world-class facilities.",
    ownerId: "u3",
    ownerName: "Marcus Johnson",
    tags: ["Executive", "Premium", "Enterprise"],
    featured: true,
    occupancy: 70,
  },
  {
    id: "ws3",
    name: "Creative Collective",
    type: "hot-desk",
    location: "Wicker Park, Chicago",
    address: "1561 N Milwaukee Ave, Chicago, IL 60622",
    city: "Chicago",
    country: "USA",
    pricePerHour: 18,
    pricePerDay: 55,
    pricePerMonth: 550,
    rating: 4.7,
    reviewCount: 203,
    capacity: 120,
    available: true,
    images: [
      "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=500&fit=crop",
    ],
    amenities: ["Wi-Fi", "Art Studio", "Coffee Bar", "Events Space", "Dog Friendly", "Bike Storage"],
    description: "A vibrant creative coworking space in the heart of Chicago's arts district. Home to designers, artists, writers, and creative entrepreneurs.",
    ownerId: "u3",
    ownerName: "Marcus Johnson",
    tags: ["Creative", "Arts", "Community"],
    featured: false,
    occupancy: 62,
  },
  {
    id: "ws4",
    name: "Tech Campus Austin",
    type: "dedicated-desk",
    location: "East Austin",
    address: "2200 E 6th St, Austin, TX 78702",
    city: "Austin",
    country: "USA",
    pricePerHour: 30,
    pricePerDay: 90,
    pricePerMonth: 950,
    rating: 4.6,
    reviewCount: 178,
    capacity: 60,
    available: true,
    images: [
      "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=500&fit=crop",
    ],
    amenities: ["Gigabit Wi-Fi", "Standing Desks", "Meditation Room", "Podcast Studio", "EV Charging", "Gym"],
    description: "Austin's fastest-growing tech campus with cutting-edge facilities, dedicated desks, and a thriving startup ecosystem.",
    ownerId: "u3",
    ownerName: "Marcus Johnson",
    tags: ["Tech", "Startup", "Dedicated"],
    featured: true,
    occupancy: 91,
  },
  {
    id: "ws5",
    name: "Harbor Meeting Suites",
    type: "meeting-room",
    location: "Waterfront, Seattle",
    address: "1301 Western Ave, Seattle, WA 98101",
    city: "Seattle",
    country: "USA",
    pricePerHour: 65,
    pricePerDay: 400,
    pricePerMonth: 2200,
    rating: 4.9,
    reviewCount: 67,
    capacity: 30,
    available: true,
    images: [
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&h=500&fit=crop",
    ],
    amenities: ["AV Equipment", "Video Conferencing", "Whiteboard", "Catering", "Harbor Views", "Valet"],
    description: "Premium meeting suites overlooking Seattle's beautiful harbor. Ideal for client presentations, board meetings, and executive workshops.",
    ownerId: "u3",
    ownerName: "Marcus Johnson",
    tags: ["Meeting Rooms", "Premium", "Views"],
    featured: false,
    occupancy: 45,
  },
  {
    id: "ws6",
    name: "Sunrise Cowork Miami",
    type: "hot-desk",
    location: "Brickell, Miami",
    address: "801 Brickell Ave, Miami, FL 33131",
    city: "Miami",
    country: "USA",
    pricePerHour: 22,
    pricePerDay: 65,
    pricePerMonth: 700,
    rating: 4.5,
    reviewCount: 134,
    capacity: 100,
    available: true,
    images: [
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=500&fit=crop",
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=500&fit=crop",
    ],
    amenities: ["Rooftop Terrace", "Pool Access", "Wi-Fi", "Coffee", "Events", "Lounge"],
    description: "Work in paradise at Miami's most vibrant coworking destination. Features a stunning rooftop terrace with ocean views and an energetic community.",
    ownerId: "u3",
    ownerName: "Marcus Johnson",
    tags: ["Lifestyle", "Community", "Tropical"],
    featured: true,
    occupancy: 78,
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    workspaceId: "ws1",
    workspaceName: "The Innovation Hub",
    workspaceImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
    userId: "u1",
    userName: "Alex Rivera",
    startDate: "2026-05-25",
    endDate: "2026-05-25",
    startTime: "09:00",
    endTime: "17:00",
    duration: "8 hours",
    type: "daily",
    seats: 1,
    totalPrice: 75,
    status: "confirmed",
    paymentStatus: "paid",
    bookingCode: "SPB-20260525-001",
    createdAt: "2026-05-20",
    notes: "Need access to the podcast studio if available.",
  },
  {
    id: "b2",
    workspaceId: "ws2",
    workspaceName: "SkyView Executive Suites",
    workspaceImage: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400&h=250&fit=crop",
    userId: "u2",
    userName: "Sarah Chen",
    startDate: "2026-05-22",
    endDate: "2026-06-22",
    startTime: "08:00",
    endTime: "20:00",
    duration: "1 month",
    type: "monthly",
    seats: 5,
    totalPrice: 3500,
    status: "checked-in",
    paymentStatus: "paid",
    bookingCode: "SPB-20260522-002",
    createdAt: "2026-05-15",
  },
  {
    id: "b3",
    workspaceId: "ws5",
    workspaceName: "Harbor Meeting Suites",
    workspaceImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop",
    userId: "u1",
    userName: "Alex Rivera",
    startDate: "2026-05-28",
    endDate: "2026-05-28",
    startTime: "14:00",
    endTime: "17:00",
    duration: "3 hours",
    type: "hourly",
    seats: 10,
    totalPrice: 195,
    status: "confirmed",
    paymentStatus: "paid",
    bookingCode: "SPB-20260528-003",
    createdAt: "2026-05-19",
  },
  {
    id: "b4",
    workspaceId: "ws3",
    workspaceName: "Creative Collective",
    workspaceImage: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=400&h=250&fit=crop",
    userId: "u1",
    userName: "Alex Rivera",
    startDate: "2026-04-10",
    endDate: "2026-04-10",
    startTime: "10:00",
    endTime: "18:00",
    duration: "8 hours",
    type: "daily",
    seats: 1,
    totalPrice: 55,
    status: "completed",
    paymentStatus: "paid",
    bookingCode: "SPB-20260410-004",
    createdAt: "2026-04-05",
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: "e1",
    title: "Tech Founders Networking Night",
    description: "Connect with 200+ tech founders, VCs, and startup leaders at our flagship monthly networking event. Perfect for early-stage founders looking for co-founders, advisors, and investors.",
    date: "2026-06-05",
    time: "18:00",
    location: "The Innovation Hub, San Francisco",
    type: "networking",
    attendees: 156,
    maxAttendees: 200,
    price: 0,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop",
    organizer: "Spacebility Community",
    tags: ["Networking", "Startup", "Tech", "Free"],
    featured: true,
  },
  {
    id: "e2",
    title: "AI & Future of Work Workshop",
    description: "A hands-on workshop exploring how AI is transforming the workplace. Learn practical AI tools, automation strategies, and how to future-proof your career or business.",
    date: "2026-06-12",
    time: "09:00",
    location: "Tech Campus Austin",
    type: "workshop",
    attendees: 42,
    maxAttendees: 50,
    price: 49,
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop",
    organizer: "FutureWork Labs",
    tags: ["AI", "Workshop", "Career", "Technology"],
    featured: true,
  },
  {
    id: "e3",
    title: "Product Design Summit 2026",
    description: "Two-day design conference featuring industry leaders from Google, Figma, and top design agencies. Covers UX strategy, design systems, and emerging trends.",
    date: "2026-06-20",
    time: "09:00",
    location: "SkyView Executive Suites, New York",
    type: "conference",
    attendees: 280,
    maxAttendees: 300,
    price: 199,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    organizer: "Design Leaders Guild",
    tags: ["Design", "Conference", "UX", "Product"],
    featured: false,
  },
  {
    id: "e4",
    title: "Miami Startup Meetup",
    description: "Monthly casual meetup for Miami's growing startup community. Pitch ideas, find collaborators, and enjoy the sunset views from our rooftop terrace.",
    date: "2026-06-15",
    time: "17:30",
    location: "Sunrise Cowork Miami",
    type: "meetup",
    attendees: 78,
    maxAttendees: 100,
    price: 0,
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&h=400&fit=crop",
    organizer: "Miami Startups Network",
    tags: ["Meetup", "Startup", "Community", "Free"],
    featured: false,
  },
  {
    id: "e5",
    title: "Remote Work Mastery Webinar",
    description: "Learn productivity hacks, async communication strategies, and tools to thrive as a remote worker or distributed team. Featuring top remote work experts.",
    date: "2026-05-28",
    time: "12:00",
    location: "Online",
    type: "webinar",
    attendees: 423,
    maxAttendees: 1000,
    price: 0,
    image: "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=600&h=400&fit=crop",
    organizer: "Spacebility",
    tags: ["Remote Work", "Webinar", "Productivity", "Free"],
    featured: true,
  },
];

export const PRICING_PLANS: Plan[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    billingPeriod: "month",
    description: "Perfect for individuals exploring flexible workspaces.",
    features: [
      "5 bookings per month",
      "Hot desk access",
      "Community access",
      "Basic analytics",
      "Email support",
      "Mobile app",
    ],
    highlighted: false,
    cta: "Start Free",
    color: "from-slate-400 to-slate-600",
  },
  {
    id: "starter",
    name: "Starter",
    price: 29,
    billingPeriod: "month",
    description: "For freelancers and remote workers who need flexibility.",
    features: [
      "20 bookings per month",
      "Hot desk + dedicated desk",
      "Meeting room credits (4hr/mo)",
      "AI workspace recommendations",
      "Priority support",
      "Team member (1 extra)",
      "Booking history & analytics",
    ],
    highlighted: false,
    cta: "Get Started",
    color: "from-cyan-400 to-cyan-600",
  },
  {
    id: "professional",
    name: "Professional",
    price: 79,
    billingPeriod: "month",
    description: "For growing teams that need reliable workspace access.",
    features: [
      "Unlimited bookings",
      "All workspace types",
      "Meeting rooms (20hr/mo)",
      "Advanced AI insights",
      "Up to 5 team members",
      "Custom branding",
      "API access",
      "Dedicated account manager",
      "Priority customer support",
    ],
    highlighted: true,
    cta: "Most Popular",
    color: "from-primary-500 to-primary-700",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 299,
    billingPeriod: "month",
    description: "For enterprises needing full workspace ecosystem control.",
    features: [
      "Everything in Professional",
      "Unlimited team members",
      "Unlimited meeting rooms",
      "Custom workspace solutions",
      "SLA guarantees",
      "SSO & SAML support",
      "Custom integrations",
      "Dedicated infrastructure",
      "24/7 phone support",
      "Quarterly business reviews",
    ],
    highlighted: false,
    cta: "Contact Sales",
    color: "from-secondary to-slate-900",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    userId: "u1",
    userName: "Alex Rivera",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    workspaceId: "ws1",
    rating: 5,
    comment: "The Innovation Hub has completely transformed how I work. The community is incredible, the internet is blazing fast, and the location is perfect. Best coworking investment I've made!",
    date: "2026-04-15",
    helpful: 24,
  },
  {
    id: "r2",
    userId: "u2",
    userName: "Sarah Chen",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    workspaceId: "ws2",
    rating: 5,
    comment: "We moved our entire startup team to SkyView Executive Suites and the impact has been remarkable. The prestige of the address, the incredible views, and the professional atmosphere have elevated our client meetings significantly.",
    date: "2026-05-10",
    helpful: 31,
  },
  {
    id: "r3",
    userId: "u4",
    userName: "Emma Wilson",
    userAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    workspaceId: "ws3",
    rating: 4,
    comment: "Creative Collective has the best community vibe I've experienced in a coworking space. The art studio access is a huge bonus and the coffee bar is top-notch. Only wish they had more phone booths.",
    date: "2026-03-22",
    helpful: 18,
  },
  {
    id: "r4",
    userId: "u3",
    userName: "Marcus Johnson",
    userAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    workspaceId: "ws4",
    rating: 5,
    comment: "Tech Campus Austin is in a league of its own. The gigabit internet handles all our dev team video calls flawlessly. The podcast studio and meditation room show they really thought through every team's needs.",
    date: "2026-05-01",
    helpful: 42,
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "blog1",
    title: "The Future of Hybrid Work: How Smart Workspaces Are Redefining the Office",
    excerpt: "As hybrid work becomes the permanent norm, flexible workspaces are evolving with AI, smart technology, and community-driven design to meet the demands of modern teams.",
    content: "",
    author: "Sarah Chen",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    date: "2026-05-15",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
    category: "Industry Trends",
    tags: ["Hybrid Work", "Future of Work", "AI", "Workspace"],
    featured: true,
  },
  {
    id: "blog2",
    title: "10 Productivity Hacks for Remote Workers Using Coworking Spaces",
    excerpt: "Maximize your productivity and work-life balance with these proven strategies for getting the most out of flexible coworking memberships.",
    content: "",
    author: "Alex Rivera",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    date: "2026-05-08",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=400&fit=crop",
    category: "Productivity",
    tags: ["Productivity", "Remote Work", "Tips", "Work-Life Balance"],
    featured: false,
  },
  {
    id: "blog3",
    title: "How Startups Are Saving $500K/Year by Ditching Traditional Leases",
    excerpt: "The math is clear: flexible workspace memberships offer early-stage startups enterprise-grade facilities at a fraction of the cost of traditional office leases.",
    content: "",
    author: "Emma Wilson",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    date: "2026-04-28",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=400&fit=crop",
    category: "Business",
    tags: ["Startup", "Cost Savings", "Business Strategy", "Coworking"],
    featured: true,
  },
  {
    id: "blog4",
    title: "Building Your Network at Coworking Spaces: A Complete Guide",
    excerpt: "Coworking spaces are the new professional networks. Learn how to leverage community events, shared spaces, and digital tools to build meaningful connections.",
    content: "",
    author: "Marcus Johnson",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    date: "2026-04-15",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&h=400&fit=crop",
    category: "Community",
    tags: ["Networking", "Community", "Career Growth", "Events"],
    featured: false,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "Booking Confirmed",
    message: "Your booking at The Innovation Hub for May 25th has been confirmed. Booking code: SPB-20260525-001",
    type: "booking",
    read: false,
    createdAt: "2026-05-20T10:30:00",
    actionUrl: "/dashboard/bookings",
  },
  {
    id: "n2",
    title: "New Event in Your Area",
    message: "Tech Founders Networking Night on June 5th — 44 spots remaining. Register now!",
    type: "event",
    read: false,
    createdAt: "2026-05-19T14:00:00",
    actionUrl: "/events",
  },
  {
    id: "n3",
    title: "Payment Successful",
    message: "Your Professional plan subscription has been renewed. Next billing date: June 20, 2026.",
    type: "payment",
    read: true,
    createdAt: "2026-05-18T09:15:00",
    actionUrl: "/dashboard/billing",
  },
  {
    id: "n4",
    title: "AI Workspace Match",
    message: "Based on your work patterns, Tech Campus Austin matches 96% of your preferences. View details.",
    type: "system",
    read: false,
    createdAt: "2026-05-17T16:45:00",
    actionUrl: "/marketplace/ws4",
  },
  {
    id: "n5",
    title: "Community Update",
    message: "Emma Wilson posted in the Freelancers Community group: 'Looking for a UX collaborator for a 2-month project'.",
    type: "community",
    read: true,
    createdAt: "2026-05-16T11:20:00",
    actionUrl: "/community",
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2026-0520",
    date: "2026-05-20",
    dueDate: "2026-06-20",
    amount: 79,
    status: "paid",
    description: "Professional Plan - May 2026",
    items: [
      { name: "Professional Plan (Monthly)", qty: 1, price: 79 },
    ],
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2026-0420",
    date: "2026-04-20",
    dueDate: "2026-05-20",
    amount: 79,
    status: "paid",
    description: "Professional Plan - April 2026",
    items: [
      { name: "Professional Plan (Monthly)", qty: 1, price: 79 },
    ],
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2026-0320",
    date: "2026-03-20",
    dueDate: "2026-04-20",
    amount: 79,
    status: "paid",
    description: "Professional Plan - March 2026",
    items: [
      { name: "Professional Plan (Monthly)", qty: 1, price: 79 },
    ],
  },
];

export const ANALYTICS_DATA: AnalyticsData = {
  revenue: [
    { month: "Jan", value: 42000 },
    { month: "Feb", value: 48000 },
    { month: "Mar", value: 55000 },
    { month: "Apr", value: 61000 },
    { month: "May", value: 70000 },
    { month: "Jun", value: 78000 },
  ],
  bookings: [
    { month: "Jan", value: 380 },
    { month: "Feb", value: 420 },
    { month: "Mar", value: 490 },
    { month: "Apr", value: 530 },
    { month: "May", value: 620 },
    { month: "Jun", value: 710 },
  ],
  occupancy: [
    { day: "Mon", value: 72 },
    { day: "Tue", value: 85 },
    { day: "Wed", value: 91 },
    { day: "Thu", value: 88 },
    { day: "Fri", value: 76 },
    { day: "Sat", value: 48 },
    { day: "Sun", value: 31 },
  ],
  userGrowth: [
    { month: "Jan", value: 1200 },
    { month: "Feb", value: 1450 },
    { month: "Mar", value: 1720 },
    { month: "Apr", value: 2100 },
    { month: "May", value: 2580 },
    { month: "Jun", value: 3100 },
  ],
};

export const WORKSPACE_AMENITIES = [
  "Wi-Fi", "Coffee & Tea", "Printing", "Phone Booths", "24/7 Access",
  "Parking", "Bike Storage", "Gym", "Shower", "Standing Desks",
  "Conference Rooms", "Event Space", "Rooftop", "Lounge", "Kitchen",
  "Mail Handling", "Receptionist", "AV Equipment", "Podcast Studio",
  "EV Charging", "Dog Friendly", "Meditation Room",
];

export const CITIES = ["San Francisco", "New York", "Chicago", "Austin", "Seattle", "Miami", "Boston", "Los Angeles", "Denver", "Atlanta"];

export const WORKSPACE_TYPES = [
  { value: "hot-desk", label: "Hot Desk" },
  { value: "dedicated-desk", label: "Dedicated Desk" },
  { value: "private-office", label: "Private Office" },
  { value: "meeting-room", label: "Meeting Room" },
  { value: "event-space", label: "Event Space" },
];

export const TRUSTED_BRANDS = [
  { name: "Stripe", logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=120&h=60&fit=crop" },
  { name: "Notion", logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=120&h=60&fit=crop" },
  { name: "Figma", logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=120&h=60&fit=crop" },
  { name: "Vercel", logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=120&h=60&fit=crop" },
  { name: "Linear", logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=120&h=60&fit=crop" },
  { name: "Loom", logo: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=120&h=60&fit=crop" },
];
